bashrc

diff --git a/configs/archlenovop52/home/labin/.local/bin/fzpm b/configs/archlenovop52/home/labin/.local/bin/fzpm
--- a/configs/archlenovop52/home/labin/.local/bin/fzpm
+++ b/configs/archlenovop52/home/labin/.local/bin/fzpm
@@ -1,5 +1,11 @@
 # fzf and paru
 fzpm() {
+    # Check if fzf and paru are installed
+    if ! command -v fzf &>/dev/null || ! command -v paru &>/dev/null; then
+        echo "Error: fzf and paru are not installed."
+        return 1
+    fi
+
     # Command to list all packages with colored tick mark
     list_cmd="paru -Sl | awk '{print (\$4 == \"[installed]\" ? \"\\033[38;2;26;127;55m✔\\033[0m\" : \"▫\") \" \" \$2, \"(\"\$1\")\"}'"
 
diff --git a/configs/archlenovop52/home/labin/.local/bin/fztmx b/configs/archlenovop52/home/labin/.local/bin/fztmx
--- a/configs/archlenovop52/home/labin/.local/bin/fztmx
+++ b/configs/archlenovop52/home/labin/.local/bin/fztmx
@@ -1,5 +1,11 @@
 # fzf and tmux sessions
 fztmx() {
+    # Check if tmux and fzf are installed
+    if ! command -v tmux &> /dev/null || ! command -v fzf &> /dev/null; then
+        echo "Error: tmux and fzf are required for this script." >&2
+        return 1
+    fi
+
     # List all sessions except the current one
     list_cmd="tmux list-sessions"
 
